FROM dockerfile/java:oracle-java8

VOLUME /tmp
ADD projectName.jar /opt/projectName/
EXPOSE 8080
WORKDIR /opt/projectName/
ENTRYPOINT ["java", "-Djava.security.egd=file:/dev/./urandom", "-Xms512m", "-Xmx1g", "-jar", "projectName.jar"]
